### ISSUE TITLE
sendRequest function always return false for all drivers

### ISSUE THREAD

**Issue by mshifo** [matthewbdaly/laravel-sms#1]
any request always return false for all drivers because there is if condition to check if status code = 201 while it returns 200 
```
return $response->getStatusCode() == 201;
```
![screenshot from 2018-06-14 12-06-11](https://user-images.githubusercontent.com/15183005/41405983-6c5cd3ac-6fcb-11e8-9d69-12aa5c2edc0d.png)

**Comment by matthewbdaly** [comment]
This is not an issue with this package as it's just a service provider for the SMS client. Please file it under https://github.com/matthewbdaly/sms-client
