### ISSUE TITLE
AWS Sender ID

### ISSUE THREAD

**Issue by tomasz-ruszel** [matthewbdaly/laravel-sms#2]
in array 'SenderID' => $message['from'] replace to 'MessageAttributes' => [
                      'AWS.SNS.SMS.SenderID' => [
                           'DataType' => 'String',
                           'StringValue' => $message['from']
                    ]
                 ]

**Comment by matthewbdaly** [comment]
You're going to have to help me out here. I have no context for this.

Is this an error message you're seeing? Or is it a change that needs applying - if so, it should really be a pull request.

Also, this package is just a service provider and factory for `matthewbdaly/sms-client`, so it's quite likely any issue is actually there.

**Comment by matthewbdaly** [comment]
Closing as I have had no response and this issue doesn't give me anything to go on.
